version: '3.8'

services:
  database:
    image: postgres:14-alpine
    container_name: sass_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      - sass

  redis:
    image: redis:7-alpine
    container_name: sass_redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./.docker/redis-data:/data
    networks:
      - sass

networks:
  sass:
    driver: bridge
